### ISSUE TITLE
For Approval window

### ISSUE THREAD

**Issue by franzegos** [CoteriePH/rdi-payroll-system#239]
MEMO (Eto sa for approval na tab)
![image.png](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/928c5cea-4c3c-45d5-8079-faee57cdac14)

MEMO.clicked
![image.png](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/7ad330c6-7356-41f8-ad6e-fc6f3086d573)

REQUEST.CA (Sa reports na tab muna since wala paglalagyan ililipat nalnag din siguro?) 
![image.png](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/68f93282-6e48-449f-ad8e-a3154785481a)

REQUEST.OTHERS
![image.png](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/03489b9d-9e80-4fc0-bf8f-7206c0de4296)

**Comment by yell66w** [comment]
#259 
#253
